### ISSUE TITLE
101 errors just when using the package

### ISSUE THREAD

**Issue by juengling** [tweh/menukeys#52]
With this minimal example ...

    \documentclass{scrartcl}
    \usepackage[os=win]{menukeys}

    \begin{document}

    \section{This is a test}

    Menu entry: \menu{This>is>a>menu>item}

    Directory: The program is installed to \directory{C:/Program Files/MyAwesomePgm}

    Keystrokes: Please press \keys{\shift + F1} to get help for the element you're pointing to.

    \end{document}

... I always get 101 errors, where the first one is this:

    ! Undefined control sequence.
    l.1793 \__msg_kernel_new:nnnn
                                  { xparse } { bad-arg-spec }
    The control sequence at the end of the top line
    of your error message was never \def'ed. If you have
    misspelled it (e.g., `\hobx'), type `I' and the correct
    spelling (e.g., `I\hbox'). Otherwise just continue,
    and I'll forget about whatever was undefined.

And then:

    ! LaTeX Error: Missing \begin{document}.

I have updated every installed package of MikTeX 2.9 on a Windows 10 (32 Bit), which is running in a Virtual Box and has provided 3.5 GB RAM.

Please find the log file attached.

[mkeys-mwe.log](https://github.com/tweh/menukeys/files/2149734/mkeys-mwe.log)

**Comment by tweh** [comment]
As I already said in my mail, this is not a problem of `menukeys` (as far as I can tell). The error message belongs to `xparse`. Try to compile your above example with `xparse` instead of `menukeys` and see if you get the same error. I guess there is something wring with our package versions, at leat I can’t reproduce your error. If you add `\filelist` to the begin of your document you can check which package versions are used, this is my list:

```
*File List*
scrartcl.cls    2018/03/30 v3.25 KOMA-Script document class (article)
scrkbase.sty    2018/03/30 v3.25 KOMA-Script package (KOMA-Script-dependent bas
ics and keyval usage)
scrbase.sty    2018/03/30 v3.25 KOMA-Script package (KOMA-Script-independent b
asics and keyval usage)
 keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
scrlfile.sty    2018/03/30 v3.25 KOMA-Script package (loading files)
tocbasic.sty    2018/03/30 v3.25 KOMA-Script package (handling toc-files)
scrsize11pt.clo    2018/03/30 v3.25 KOMA-Script font size class option (11pt)
typearea.sty    2018/03/30 v3.25 KOMA-Script package (type area)
menukeys.sty    2016/08/08 v1.5 -- A package to format menus, paths and shortcu
ts
 xparse.sty    2018-05-12 L3 Experimental document command parser
  expl3.sty    2018-06-14 L3 programming layer (loader) 
expl3-code.tex    2018-06-14 L3 programming layer 
l3pdfmode.def    2018-06-14 v L3 Experimental driver: PDF mode
xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
etoolbox.sty    2018/02/11 v2.5e e-TeX tools for LaTeX (JAW)
   tikz.sty    2015/08/07 v3.0.1a (rcs-revision 1.151)
    pgf.sty    2015/08/07 v3.0.1a (rcs-revision 1.15)
 pgfrcs.sty    2015/08/07 v3.0.1a (rcs-revision 1.31)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
 pgfrcs.code.tex
pgfcore.sty    2010/04/11 v3.0.1a (rcs-revision 1.7)
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
   trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
 pdftex.def    2018/01/08 v1.0l Graphics/color driver for pdftex
 pgfsys.sty    2014/07/09 v3.0.1a (rcs-revision 1.48)
 pgfsys.code.tex
pgfsyssoftpath.code.tex    2013/09/09  (rcs-revision 1.9)
pgfsysprotocol.code.tex    2006/10/16  (rcs-revision 1.4)
 xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
  color.cfg    2016/01/02 v1.6 sample color configuration
pgfcore.code.tex
pgfcomp-version-0-65.sty    2007/07/03 v3.0.1a (rcs-revision 1.7)
pgfcomp-version-1-18.sty    2007/07/23 v3.0.1a (rcs-revision 1.1)
 pgffor.sty    2013/12/13 v3.0.1a (rcs-revision 1.25)
pgfkeys.sty    
pgfkeys.code.tex
pgfmath.sty    
pgfmath.code.tex
 pgffor.code.tex
   tikz.code.tex
adjustbox.sty    2018/04/08 v1.1 Adjusting TeX boxes (trim, clip, ...)
xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
adjcalc.sty    2012/05/16 v1.1 Provides advanced setlength with multiple back-
ends (calc, etex, pgfmath)
trimclip.sty    2018/04/08 v1.1 Trim and clip general TeX material
collectbox.sty    2012/05/17 v0.4b Collect macro arguments as boxes
tc-pdftex.def    2018/04/08 v2.1 Clipping driver for pdftex
ifoddpage.sty    2016/04/23 v1.1 Conditionals for odd/even page detection
varwidth.sty    2009/03/30 ver 0.92;  Variable-width minipages
relsize.sty    2013/03/29 ver 4.1
catoptions.sty    2014/08/29 v0.2.7h Securing catcodes and parsing options (AM)

kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
supp-pdf.mkii
epstopdf-base.sty    2016/05/15 v2.6 Base part for package epstopdf
 grfext.sty    2016/05/16 v1.2 Manage graphics extensions (HO)
kvdefinekeys.sty    2016/05/16 v1.4 Define keys (HO)
pdftexcmds.sty    2018/01/30 v0.27 Utility functions of pdfTeX for LuaTeX (HO)
  ifpdf.sty    2017/03/15 v3.2 Provides the ifpdf switch
epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
***********
```

**Comment by juengling** [comment]
Thanks for the list, and very sorry for not answering to your mail - GMX must have eaten it.

I guess you meant `\filelist`? I have no chance to see it, because pdflatex always stop after 100 errors, and I didn't find any command to tell it to go on. At least my xparse.sty and l3pdfmode.def in the MikTeX folder are of same date as yours.

**Comment by tweh** [comment]
Try to save this

```tex
\listfiles
\documentclass{article}

\usepackage{menukeys}

\begin{document}
Test
\end{document}
```

as `test.tex` and run

```
pdflatex -interaction=nonstopmode test.tex
```
 in that case you’ll at least should get a LOG file containing the file list. Next step: replace `menukeys` in `text.tex` with `xparse` and run it again. Do you still get errors?

**Comment by juengling** [comment]
With both `menukeys` and `xparse` I get 100 errors and no file list at all. What I don't understand is, that the xparse.sty file contains

    \ProvidesExplPackage{xparse}{2018-05-12}{}{L3 Experimental document command parser}

... while the error log says

    Package: xparse 2017/12/16 L3 Experimental document command parser

There is no other xparse.sty on my hard disk.

**Comment by tweh** [comment]
Well in that case – as I guessed – it is not a problem of `menukeys` … However it seems like your distribution is somehow corrupted. I fear I can’t help you further since I have no experience with MikTeX. You can try to completly uninstall and reinstall TeX, but I don’t know if that helps.

You might also try to ask for help at https://tex.stackexchange.com.

**Comment by juengling** [comment]
Indeed it is. I tried it at another PC with a fresh MikTeX installation, and everything is fine. Thanks for your help :-)
