### ISSUE TITLE
Loading before babel

### ISSUE THREAD

**Issue by jspitz** [tweh/menukeys#53]
Since it's not documented: If I load the package before babel, i get

> ! Package catoptions Error: '\XDeclareOption*' multiply defined in 
> (catoptions)                package 'babel'.

If this cannot be resolved, it should at least be documented.

MWE:

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[latin9]{inputenc}

\usepackage{menukeys}
\usepackage{babel}

\begin{document}
\cmd
\end{document}
```

**Comment by tweh** [comment]
The documentation says that `menukeys` should be loaded as the last package. Which includes after `babel` in my eyes. See sec. 3, p. 5:

> Since `menukeys` uses `catoptions`, which does some heavy changes on key-value options, it is recommended to load menukeys as the **last package** (even after `hyperref`)!

**Comment by jspitz** [comment]
Sorry, I should have looked closer.
