### ISSUE TITLE
\backtab

### ISSUE THREAD

**Issue by jspitz** [tweh/menukeys#54]
Could you add the macro `\backtab`, which represents the character 'LEFTWARDS ARROW TO BAR' (U+21E4)? This is sometimes used for Shift-Tab (e.g. by [QKeySequence::toString](http://doc.qt.io/qt-5/qkeysequence.html#toString))

It basically would just need the `\tabmac` macro mirrored.

**Comment by tweh** [comment]
I merged this request in issue #5. But I’m not sure when I’ll have the time to do so. If you use a unicode-able editor and a font it should be possible to add these symbols directly.
