### ISSUE TITLE
Keys height when using Crimson Text from Google Fonts

### ISSUE THREAD

**Issue by calben** [tweh/menukeys#55]
Hey everyone,

I'd like to use the menukeys package for some documentation I'm writing, and the samples look amazing.
However, I'd like to use Crimson Text for my document.
When I do so, the key height is incorrect, covering about the bottom fourth of a letter.
When I switch to, say, Montserrat or Inconsolata, everything is fine again.

What sort of information is missing from Crimson Text and can I supply it some other way?

Thanks!

**Comment by calben** [comment]
This is by no means urgent.  I switched to use PT Serif and everything is working fine, but it'd be nice to know for future reference :-)

**Comment by tweh** [comment]
Hm … with the following MWE and the version of Crimson installed on my system I can’t reproduce your issue.

```latex
% !TeX program = xelatex
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Crimson}
\setsansfont{Crimson}

\usepackage{menukeys}

\begin{document}
Test \menu{Test}.
\end{document}
```

Could you please test this code or provide a MWE yourself including a screenshot of the resulting PDF, please?

**Comment by Skillmon** [comment]
I close this, because it couldn't be reproduced and is inactive for more than two years now.
