### ISSUE TITLE
Style angularkeys does not separate keys

### ISSUE THREAD

**Issue by thymaro** [tweh/menukeys#56]
I changed the style of keys to `angularkeys` with

    \renewmenumacro{\keys}{angularkeys}

but doing this will include the key separator (standard: "+") and just draw one long box around the key stroke combination.

**Comment by tweh** [comment]
Yes, you have to use the optional argument to let `+` be still the separator. Otherwise the default (`,`) is used. So your line should read

    \renewmenumacro{\keys}[+]{angularkeys}

**Comment by thymaro** [comment]
that clears it up. thanks Tobi

**Comment by tweh** [comment]
You‘re welcome! :-)
