### ISSUE TITLE
hope to have an 'auto' option for operating system

### ISSUE THREAD

**Issue by zhyiyu** [tweh/menukeys#58]
Would it be nice if the option `os` can take in a value like `auto` such that it recognizes where this document is being compiled? Currently I am doing

```latex
\usepackage{ifplatform}
\ifwindows
\usepackage[os = win]{menukeys}
\else
\usepackage[os = mac]{menukeys}
\fi
```

thanks!

**Comment by tweh** [comment]
Hi,

thanks for your feedback, but I think a feature like this would lead to some chaos since not all short cuts translate 1:1 from one to another OS and I’d say the author of a document (not the person who compiles it or his/her OS) should control how the keys look like. Don’t you think?

**Comment by zhyiyu** [comment]
Yes, you are right.
