### ISSUE TITLE
Compilation error with menukeys, probably due to catoptions

### ISSUE THREAD

**Issue by dbitouze** [tweh/menukeys#59]
The following MWE points out a trouble, I guess due to the recent (2020-10-01) LaTeX release, with the `catoptions` package loaded by `menukeys`:
```latex
\documentclass{article}
\usepackage{menukeys}
\begin{document}
\end{document}
```
leads to:
```
! Extra \endgroup.
\document ->\endgroup 
                      \let \BeforeStartOfDocument \@firstofone \cpt@beforest...
l.20 \begin{document}
                     
? 
(./test.aux)
(/home/bitouze/texlive/2020/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)
(/home/bitouze/texlive/2020/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/home/bitouze/texlive/2020/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
 (./test.aux) )
(\end occurred inside a group at level 1)

### semi simple group (level 1) entered at line 20 (\begingroup)
### bottom level
```

**Comment by dulimarta** [comment]
I got the same issue after updating my LaTeX packages two days ago (Oct 6). Is there a way to downgrade either catoptions or menukeys?

**Comment by Toromtomtom** [comment]
I reverted with `tlmgr` by doing
```
$ tlmgr restore latex
Available backups for latex: 53958 (2020-10-08 13:20)
$ tlmgr restore latex 53958
```
and now I can compile documents using `menukeys` again without any error.

**Comment by tweh** [comment]
Im sorry for the inconvenience. I was aware of this issue beforehand but unfortunately had no spare time to investigate further or having a fix ready. At the moment I can’t tell when I find some time to dive in, but I hope it will be soon. Until then the only way of using `menukeys` is with an older version of LaTeX. Since the issues come from incompatibilities between the LaTeX kernel and `catoptions` it won’t work to only downgrade `menukeys` or `catoptions`.

**Comment by u-fischer** [comment]
another option until the package is fixed is to use latexrelease (this requires `LaTeX2e <2020-10-01> patch level 1` as this fixed a bug in the release guards). With latexrelease you are "going back" to an older latex, so menukeys no longer errors, but the new features or the current latex aren't available either:

~~~~
\RequirePackage[2020-02-02]{latexrelease}
\documentclass{article}

\usepackage{menukeys}%


\begin{document}

\section{Menukeys test}

Where is the issue ? \menu{File>New File}

\end{document}
~~~~

**Comment by Skillmon** [comment]
This would be fixed by https://github.com/tweh/menukeys/pull/60.
