### ISSUE TITLE
menukeys seems to prevent another package from running \addtocontents

### ISSUE THREAD

**Issue by madmurphy** [tweh/menukeys#68]
Hi Tobias,

I am the author of the [`hereapplies`](https://github.com/madmurphy/hereapplies.sty) LaTeX package. Could you please have a look at [this discussion](https://github.com/madmurphy/hereapplies.sty/issues/1)?

--madmurphy

**Comment by Skillmon** [comment]
This is not a `menukeys` issue, see https://github.com/madmurphy/hereapplies.sty/issues/1#issuecomment-1344802348
